### ISSUE TITLE
Scenario API

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/vindinium_bot#2]
The bot will need to be aware of possible scenarios that may arise, and obstacles that the bot needs to be aware of. An example of both would be the bot avoiding a healthy player on the way to the tavern to refill it's HP. We will need to determine the possible scenarios that arise, and a `move_to` target to acquire before running the pathfinding algorithm.

This API should determine the best course of action each turn by utilizing a flowchart-like decision tree. More brainstorming should be done on this.

**Comment by BrianErikson** [comment]
![decision tree v1](https://cloud.githubusercontent.com/assets/7645647/16356331/0e87a492-3ad4-11e6-81aa-96306b5f7a13.png)

**Comment by PurityLake** [comment]
Well one thing that should be checked as regards claiming the mine is that the health is high enough to survive the encounter

Also a check that it is possible to reach a tavern as it might be in a corridor that is blocked by another hero

**Comment by BrianErikson** [comment]
added basic logic system ending on commit 94eee28bc0e3e5ad4c1c8526e19dcfd18ed45367
